In [7]:
import tensorflow as tf
import json
import nn_models as nnm
import dataprocessing as dp

In [2]:
folder = 'test_logistic_43-cm_hypertuning_results'
subfolder = 'indv_43-cm_both_dlh2_classification_downsample_Epochs1000_None'
epochs = 100
best_model_path = f'../Results/{folder}/{subfolder}/lstm_results/{epochs}'
hypermodel = tf.saved_model.load(best_model_path)

2023-11-04 10:40:47.979436: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [11]:
model = tf.keras.models.load_model(best_model_path)

In [20]:
model.compiled_loss.build(target)

In [25]:
model.compile(loss = 'binary_crossentropy')

In [30]:
model.loss

'binary_crossentropy'

In [24]:
model.build()
model.predict(data)

88/88 [==============================] - 0s 3ms/step


array([[0.546823  ],
       [0.54900146],
       [0.55093443],
       ...,
       [0.5359753 ],
       [0.52988124],
       [0.5254486 ]], dtype=float32)

In [12]:
dir(model)

['_SCALAR_UPRANKING_ON',
 '_TF_MODULE_IGNORED_PROPERTIES',
 '__annotations__',
 '__call__',
 '__class__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_activity_regularizer',
 '_add_trackable',
 '_add_trackable_child',
 '_add_variable_with_custom_getter',
 '_assert_compile_was_called',
 '_assert_weights_created',
 '_auto_track_sub_layers',
 '_autocast',
 '_autographed_call',
 '_base_model_initialized',
 '_build_graph_network_for_inferred_shape',
 '_build_input_shape',
 '_call_accepts_kwargs',
 '_call_arg_was_passed',
 '_call_fn_arg_defaults',
 '_call_fn_arg_positions',
 '_call_fn_args',
 '_call_full_argspec',
 '_cal

In [13]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 24, 2),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'LSTM-layer-0_input'}},
  {'class_name': 'LSTM',
   'config': {'name': 'LSTM-layer-0',
    'trainable': True,
    'dtype': 'float32',
    'return_sequences': True,
    'return_state': False,
    'go_backwards': False,
    'stateful': False,
    'unroll': False,
    'time_major': False,
    'units': 54,
    'activation': 'tanh',
    'recurrent_activation': 'sigmoid',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'recurrent_initializer': {'class_name': 'Orthogonal',
     'config': {'gain': 1.0, 'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'unit_forget_bias': True,
    'kernel_regularizer': None,
    'recurrent_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,


In [3]:
loss = 'binary_crossentropy'
num_features = 1
binary = True
TIME_STEPS = 24

In [4]:
### Create model dictionary
model_dict = {'lstm':                 nnm.HyperLSTM(loss=loss, num_features=num_features, binary=binary),
              'bilstm':               nnm.HyperBiLSTM(loss=loss, num_features=num_features, binary=binary),
              'lstm-autoencoder':     nnm.HyperLSTMAutoEncoder(loss=loss, time_steps=TIME_STEPS, num_features=num_features),
              'deeplstm-autoencoder': nnm.HyperDeepLSTMAutoEncoder(loss=loss, time_steps=TIME_STEPS, num_features=num_features),
              'ann':                  nnm.HyperANN(loss=loss, num_features=num_features, binary=binary),
              'simplernn':            nnm.HyperSimpleRNN(loss=loss, num_features=num_features, binary=binary),
              'autoencoder':          nnm.HyperAutoencoder(loss=loss, num_features=num_features, binary=binary)
              #'randomforest':     nnm.HyperRandomForest()
              }

In [14]:
model.predict(data)

88/88 [==============================] - 1s 4ms/step


array([[0.546823  ],
       [0.54900146],
       [0.55093443],
       ...,
       [0.5359753 ],
       [0.52988124],
       [0.5254486 ]], dtype=float32)

In [8]:
### Load data ###
subject = '43-cm'
sensor =  'both'
dlh = 2
event = True
data, target = dp.create_featured_dataset(subject, sensor=sensor, dlh=dlh, keep_SH=False, keep_event=event, smote=None)

The beginning shape is:  (6236, 99)
After dropping rows with NaN in the SH_Event columns, the shape is:  (2804, 99)
NaN values in this dataset:  False
The left data frame set shape is:  (2804, 48)
The right data frame set shape is:  (2804, 48)
The keep left data frame set shape is:  (2804, 24)
The keep right data frame set shape is:  (2804, 24)
Not adding fake positive data samples.
Index(['t17_l', 't18_l', 't19_l', 't20_l', 't21_l', 't22_l', 't23_l', 't24_l',
       't25_l', 't26_l', 't27_l', 't28_l', 't29_l', 't30_l', 't31_l', 't32_l',
       't33_l', 't34_l', 't35_l', 't36_l', 't37_l', 't38_l', 't39_l', 't40_l'],
      dtype='object')
Index(['t17_r', 't18_r', 't19_r', 't20_r', 't21_r', 't22_r', 't23_r', 't24_r',
       't25_r', 't26_r', 't27_r', 't28_r', 't29_r', 't30_r', 't31_r', 't32_r',
       't33_r', 't34_r', 't35_r', 't36_r', 't37_r', 't38_r', 't39_r', 't40_r'],
      dtype='object')


In [20]:
# Load best hyperparameters
# hps_path = "../Results/3-jk_hypertuning_results/hypermodel_lstm_general_3-jk_right_dlh2_classification_Epochs100/best_hps_lstm_hypertune.json"
# with open(hps_path, 'r') as bin:
#     best_hps = json.load(bin)

In [9]:
hypermodel.predict(data)

AttributeError: '_UserObject' object has no attribute 'predict'

In [28]:
mdl = model_dict['lstm']

In [29]:
best_model = mdl.build(best_hps)

AttributeError: 'dict' object has no attribute 'Int'

In [30]:
hypermodel.build(best_hps)

AttributeError: '_UserObject' object has no attribute 'build'

In [6]:
model = tf.keras.models.load_model(best_model_path)

In [9]:
dir(model)

['_SCALAR_UPRANKING_ON',
 '_TF_MODULE_IGNORED_PROPERTIES',
 '__annotations__',
 '__call__',
 '__class__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_activity_regularizer',
 '_add_trackable',
 '_add_trackable_child',
 '_add_variable_with_custom_getter',
 '_assert_compile_was_called',
 '_assert_weights_created',
 '_auto_track_sub_layers',
 '_autocast',
 '_autographed_call',
 '_base_model_initialized',
 '_build_graph_network_for_inferred_shape',
 '_build_input_shape',
 '_call_accepts_kwargs',
 '_call_arg_was_passed',
 '_call_fn_arg_defaults',
 '_call_fn_arg_positions',
 '_call_fn_args',
 '_call_full_argspec',
 '_cal

In [18]:
model.get_weights()

[array([[ 0.04409657],
        [ 0.10304586],
        [-0.21168272],
        [-0.18194027],
        [ 0.18888193],
        [ 0.1204467 ],
        [-0.02398791],
        [ 0.11232393],
        [ 0.05532508],
        [-0.20364158],
        [-0.19390255],
        [-0.02370966],
        [ 0.17881154],
        [ 0.31911996],
        [-0.03531401],
        [-0.28952077],
        [ 0.03911546],
        [-0.03585904],
        [-0.13410696],
        [ 0.2400676 ],
        [ 0.16237667],
        [ 0.00858379],
        [-0.1889712 ],
        [-0.3367601 ],
        [ 0.2029963 ],
        [ 0.3242101 ],
        [-0.14799967],
        [-0.2111747 ],
        [-0.06877846],
        [ 0.18426444],
        [ 0.02512247],
        [-0.0098769 ],
        [-0.01071386],
        [-0.06013114],
        [ 0.10082561],
        [-0.05304584],
        [-0.14052847],
        [ 0.15259661],
        [ 0.12661044],
        [-0.1761478 ],
        [-0.04157392],
        [ 0.12157863],
        [ 0.18249363],
        [-0

In [7]:
import numpy as np
test = np.array([87, 86, 89, 78, 82, 85,
                 84, 83, 82, 81, 80, 79,
                 78, 77, 76, 75, 74, 73, 
                 72, 71, 70, 65, 64, 59,
                 87, 86, 89, 78, 82, 85,
                 84, 83, 82, 81, 80, 79,
                 78, 77, 76, 75, 74, 73, 
                 72, 71, 70, 65, 64, 59,]).reshape(1,-1)
y = np.array([1]).reshape(1,-1)

In [8]:
model.evaluate(test, y)

ValueError: in user code:

    File "/Users/kirsh012/opt/anaconda3/envs/tf/lib/python3.10/site-packages/keras/engine/training.py", line 1557, in test_function  *
        return step_function(self, iterator)
    File "/Users/kirsh012/opt/anaconda3/envs/tf/lib/python3.10/site-packages/keras/engine/training.py", line 1546, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/kirsh012/opt/anaconda3/envs/tf/lib/python3.10/site-packages/keras/engine/training.py", line 1535, in run_step  **
        outputs = model.test_step(data)
    File "/Users/kirsh012/opt/anaconda3/envs/tf/lib/python3.10/site-packages/keras/engine/training.py", line 1499, in test_step
        y_pred = self(x, training=False)
    File "/Users/kirsh012/opt/anaconda3/envs/tf/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/Users/kirsh012/opt/anaconda3/envs/tf/lib/python3.10/site-packages/keras/engine/input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_2" is incompatible with the layer: expected shape=(None, 24, 2), found shape=(None, 48)


In [15]:
model.predict(test)

1/1 [==============================] - 0s 108ms/step


array([[0.5783941]], dtype=float32)

In [16]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 67)                3283      
                                                                 
 dropout_9 (Dropout)         (None, 67)                0         
                                                                 
 dense_10 (Dense)            (None, 25)                1700      
                                                                 
 dropout_10 (Dropout)        (None, 25)                0         
                                                                 
 dense_11 (Dense)            (None, 29)                754       
                                                                 
 dropout_11 (Dropout)        (None, 29)                0         
                                                                 
 dense_12 (Dense)            (None, 51)               

In [17]:
from pathlib import Path

In [18]:
test_path = Path('../Results/best_model_ann_hypertune/')

In [21]:
if (test_path / "test.npz").exists():
    print("Doesn't exist!")
else:
    print("It worked!")

It worked!


In [22]:
from tensorboard.plugins.hparams import api as hp

In [23]:
dir(hp)

['Discrete',
 'Domain',
 'HParam',
 'IntInterval',
 'KerasCallback',
 'Metric',
 'RealInterval',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'hparams',
 'hparams_config',
 'hparams_config_pb',
 'hparams_pb']

In [28]:
with tf.summary.create_file_writer("../Results/test/best_hps").as_default():
    hp.hparams({'hidden_layers': 4, 'learning_rate': 0.002, 'units-0': 235, 'dropout-0': 0.15000000000000002, 'units-1': 105, 'dropout-1': 0.4, 'units-2': 135, 'dropout-2': 0.15000000000000002, 'units-3': 95, 'dropout-3': 0.1, 'units-4': 50, 'dropout-4': 0.35000000000000003, 'tuner/epochs': 500, 'tuner/initial_epoch': 50, 'tuner/bracket': 1, 'tuner/round': 1, 'tuner/trial_id': '0153'})

In [29]:
best_hps = hp.hparams({'hidden_layers': 4, 'learning_rate': 0.002, 'units-0': 235, 'dropout-0': 0.15000000000000002, 'units-1': 105, 'dropout-1': 0.4, 'units-2': 135, 'dropout-2': 0.15000000000000002, 'units-3': 95, 'dropout-3': 0.1, 'units-4': 50, 'dropout-4': 0.35000000000000003, 'tuner/epochs': 500, 'tuner/initial_epoch': 50, 'tuner/bracket': 1, 'tuner/round': 1, 'tuner/trial_id': '0153'})

In [30]:
dir(best_hps)

['OVERLOADABLE_OPERATORS',
 '_USE_EQUALITY',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__tf_traci

In [32]:
dict(best_hps)

TypeError: Cannot iterate over a scalar tensor.

In [33]:
best_hps

<tf.Tensor: shape=(), dtype=bool, numpy=False>